// One realistic example per Visual.kind, all from the same imagined PR
// ("Add retry with exponential backoff to the HTTP client") so a preview
// reads as a single brief. Tests and the landing preview both consume this.

import type { Visual } from "@/lib/types";

export const DEMO_PR_TITLE = "Add retry with exponential backoff to the HTTP client";

export const DEMO_VISUALS: Visual[] = [
  {
    kind: "pseudocode",
    title: "Retry loop around a single request",
    body: [
      "attempt = 0",
      "loop:",
      "  response = send(request, timeout)",
      "  if response.ok or not retryable(response):",
      "    return response",
      "  attempt += 1",
      "  if attempt > policy.max_retries:",
      "    raise RetryExhausted(last=response)  # surfaces the final status",
      "  delay = backoff(attempt, policy)",
      "  if response.retry_after is set:",
      "    delay = max(delay, response.retry_after)",
      "  sleep(delay)",
    ].join("\n"),
    caption:
      "Only 408, 429, and 5xx responses (plus connection resets) are retried; every other status returns on the first pass.",
    refs: [{ path: "src/http/retry.ts", line: 18 }],
  },
  {
    kind: "call_tree",
    title: "What runs when a request fails",
    body: [
      "HttpClient.request(url, init)",
      "  withRetry(policy, attempt)  // new wrapper",
      "    fetchOnce(url, init, timeout)",
      "      AbortController.abort()  → on timeout",
      "    isRetryable(error | response)",
      "    computeDelay(attempt, policy)",
      "      jitter(base, spread)",
      "    sleep(delay, signal)",
      "  onRetry?.(attempt, delay)  // hook for metrics",
    ].join("\n"),
    caption: "Everything below withRetry() is unchanged; the wrapper is the only new control flow.",
    refs: [
      { path: "src/http/client.ts", line: 42 },
      { path: "src/http/retry.ts", line: 31 },
    ],
  },
  {
    kind: "component_tree",
    title: "Status banner wired to retry events",
    body: [
      "<RequestStatusProvider>",
      "  useHttpClient()  // subscribes to onRetry",
      "  <Toaster>",
      "    <RetryToast attempt delay />  // shown from attempt 2 onward",
      "  </Toaster>",
      "  {children}",
      "</RequestStatusProvider>",
    ].join("\n"),
    caption: "The toast is the only UI change; it reads attempt and delay straight from the retry hook.",
    refs: [{ path: "src/ui/request-status.tsx", line: 12 }],
  },
  {
    kind: "file_tree",
    title: "Where the change lives",
    body: [
      "src/http/",
      "├── client.ts        modified — wraps fetchOnce in withRetry",
      "├── retry.ts         new — policy, loop, isRetryable",
      "├── backoff.ts       new — exponential delay with full jitter",
      "└── errors.ts        modified — adds RetryExhausted",
      "tests/http/",
      "├── retry.test.ts    new — 9 cases, fake timers",
      "└── client.test.ts   modified — timeout path now asserts one retry",
      "docs/",
      "└── http.md          modified — documents the default policy",
    ].join("\n"),
    caption: null,
    refs: [
      { path: "src/http/retry.ts", line: null },
      { path: "src/http/backoff.ts", line: null },
    ],
  },
  {
    kind: "mermaid",
    title: "Request lifecycle with retries",
    body: [
      "sequenceDiagram",
      "  participant C as Caller",
      "  participant H as HttpClient",
      "  participant S as Server",
      "  C->>H: request(url)",
      "  H->>S: GET /orders",
      "  S-->>H: 503 Retry-After: 2",
      "  Note over H: delay = max(backoff(1), 2s)",
      "  H->>S: GET /orders (attempt 2)",
      "  S-->>H: 200 OK",
      "  H-->>C: Response",
    ].join("\n"),
    caption: "Retry-After wins over the computed backoff when the server sends one.",
    refs: [{ path: "src/http/retry.ts", line: 54 }],
  },
  {
    kind: "shape_diff",
    title: "HttpClient options",
    before: [
      "interface HttpClientOptions {",
      "  baseUrl: string",
      "  timeoutMs: number",
      "  headers?: Record<string, string>",
      "}",
    ].join("\n"),
    after: [
      "interface HttpClientOptions {",
      "  baseUrl: string",
      "  timeoutMs: number",
      "  headers?: Record<string, string>",
      "  retry?: RetryPolicy",
      "  onRetry?: (attempt: number, delayMs: number) => void",
      "}",
      "",
      "interface RetryPolicy {",
      "  maxRetries: number      // default 3",
      "  baseDelayMs: number     // default 200",
      "  maxDelayMs: number      // default 5_000",
      "  retryOn: number[]       // default [408, 429, 500, 502, 503, 504]",
      "}",
    ].join("\n"),
    caption: "Both new fields are optional, so existing call sites compile unchanged and get the defaults.",
    refs: [{ path: "src/http/client.ts", line: 9 }],
  },
  {
    kind: "code_block",
    title: "Full-jitter backoff",
    language: "ts",
    body: [
      "export function computeDelay(attempt: number, policy: RetryPolicy): number {",
      "  // Full jitter (AWS): random in [0, cap] avoids thundering herds better",
      "  // than equal jitter at the cost of occasionally retrying immediately.",
      "  const cap = Math.min(policy.maxDelayMs, policy.baseDelayMs * 2 ** (attempt - 1));",
      "  return Math.floor(Math.random() * cap);",
      "}",
    ].join("\n"),
    caption: "Attempt is 1-based; attempt 1 caps at baseDelayMs.",
    refs: [{ path: "src/http/backoff.ts", line: 4 }],
  },
  {
    kind: "callout",
    title: "Retries are not idempotent-safe by default",
    body: [
      "withRetry() re-sends POST and PATCH bodies whenever the status is in retryOn. A 503 after the server committed the write will replay it.",
      "Either restrict the default policy to idempotent methods or require an Idempotency-Key header before this ships.",
    ].join("\n\n"),
    tone: "warn",
    caption: null,
    refs: [{ path: "src/http/retry.ts", line: 27 }],
  },
];
